### ISSUE TITLE
decltype推断数组

### ISSUE THREAD

**Issue by FengJingkun** [Light-City/CPlusPlusThings#100]
`int arr[5] = { 0 };`
`decltype (arr) var1; `

这里var1的推断类型应该是int[5]类型吧？原文在注释中写的是int类型。

**Comment by yhjustwalking** [comment]
没看原文，但是你说的是对的

**Comment by Light-City** [comment]
> `int arr[5] = { 0 };` `decltype (arr) var1; `
> 
> 这里var1的推断类型应该是int[5]类型吧？原文在注释中写的是int类型。

是的
