### ISSUE TITLE
函数指针的问题

### ISSUE THREAD

**Issue by Willzy-x** [Light-City/CPlusPlusThings#101]
函数指针内容中的`func_pointer.cpp`里面：
``` cpp
/**
 * @brief 定义了一个变量pFun，这个变量是个指针，指向返回值和参数都是空的函数的指针！
 */
void (*pFun)(int); 

...

void glFun(int a){ cout<<a<<endl;} 

...
// main 中
pFun = glFun; 
(*pFun)(2); 
```

说`pFun`是一个指向返回值和参数都是空的函数的指针，但是在`main`中把一个返回为空但是参数是一个`int`类型的函数赋值给了`pFun`。这里不太明白，是打错了吗，还是有什么别的原因？

**Comment by lubical** [comment]
应该是打错了，返回值为空，参数为int才对。

**Comment by Light-City** [comment]
> 函数指针内容中的`func_pointer.cpp`里面：
> 
> ```c++
> /**
>  * @brief 定义了一个变量pFun，这个变量是个指针，指向返回值和参数都是空的函数的指针！
>  */
> void (*pFun)(int); 
> 
> ...
> 
> void glFun(int a){ cout<<a<<endl;} 
> 
> ...
> // main 中
> pFun = glFun; 
> (*pFun)(2); 
> ```
> 
> 说`pFun`是一个指向返回值和参数都是空的函数的指针，但是在`main`中把一个返回为空但是参数是一个`int`类型的函数赋值给了`pFun`。这里不太明白，是打错了吗，还是有什么别的原因？

已修复，这里写错了
