### ISSUE TITLE
using 改变访问性，代码似乎有bug?

### ISSUE THREAD

**Issue by xiahaifeng1995** [Light-City/CPlusPlusThings#103]
第35行派生类中应该无法通过using声明来标记基类的私有成员，该处代码编辑器报错。

**Comment by wanghengg** [comment]
第35行确实有问题，我编译运行不通过。报错为：'int Base::value' is private within this context
我的理解为：using可以提高访问性，但是仅限于将基类的protected修饰的保护类型提高为public，但是不能直接将基类的private类型提高为public，根据C++语法要求**基类中private修饰成员在派生类中不能访问，自然不能使用using提升其访问性。只有基类的protected类型，在派生类中可以访问，然后才可以用using提升为public类型。**

**Comment by wanghengg** [comment]
> 
> 
> 第35行确实有问题，我编译运行不通过。报错为：'int Base::value' is private within this context
> 我的理解为：using可以提高访问性，但是仅限于将基类的protected修饰的保护类型提高为public，但是不能直接将基类的private类型提高为public，根据C++语法要求**基类中private修饰成员在派生类中不能访问，自然不能使用using提升其访问性。只有基类的protected类型，在派生类中可以访问，然后才可以用using提升为public类型。**

![图片](https://user-images.githubusercontent.com/26854956/110120065-8499d400-7df7-11eb-8742-3267ed5ebf8a.png)
