### ISSUE TITLE
基础进阶中const那些事readme代码有误

### ISSUE THREAD

**Issue by sukusukuremi** [Light-City/CPlusPlusThings#108]
第七大点，类中使用const中
`int Apple::add(int num){
    take(num);
}
int Apple::add(int num) const{
    take(num);
}`

均没有返回值

**Comment by Light-City** [comment]
> 第七大点，类中使用const中 `int Apple::add(int num){ take(num); } int Apple::add(int num) const{ take(num); }`
> 
> 均没有返回值

突出的重点不是这一块 就没写好，已修复
