### ISSUE TITLE
sizeof 原则3

### ISSUE THREAD

**Issue by LongTengYiFei** [Light-City/CPlusPlusThings#113]
继承多个类的话，本类的虚表指针就不止一个了。

**Comment by yhjustwalking** [comment]
你看过c艹内存模型这本书的话，就知道虚表指针始终是一个

**Comment by hahaha1014** [comment]
![image](https://user-images.githubusercontent.com/57948790/143593304-e794343a-2f57-44f1-95d5-4b30b20a71bf.png)
想问一下为什么加了一个虚函数之后sizeof(A)是16，但是只有char和static int的时候是1

**Comment by Light-City** [comment]
> ![image](https://user-images.githubusercontent.com/57948790/143593304-e794343a-2f57-44f1-95d5-4b30b20a71bf.png) 想问一下为什么加了一个虚函数之后sizeof(A)是16，但是只有char和static int的时候是1

字节对齐
