### ISSUE TITLE
单例模式中基于operator new+placement new，遵循1,2,3执行顺序依次编写代码此处下的代码有误

### ISSUE THREAD

**Issue by ydszza** [Light-City/CPlusPlusThings#116]
singleton *tmp = static_cast<singleton *>(operator new(sizeof(singleton)));
new(p)singleton();
p = tmp;

我认为应该是
singleton *tmp = static_cast<singleton *>(operator new(sizeof(singleton)));
new(tmp)singleton();
p = tmp;
亦或者是我搞错了？
获取实例函数为成员函数？但是要通过该函数过去对象？
是否我理解有误，还是笔误？或者说网站未更新，此仓库更新了？

**Comment by yhjustwalking** [comment]
专门看了一下，你说的是对的，他写错了，应该是你写的那样子，不然指针p没啥用了

**Comment by liukai234** [comment]
#127 
关于此我发起了一个request

**Comment by Light-City** [comment]
写错了
