### ISSUE TITLE
智能指针是错的

### ISSUE THREAD

**Issue by chanchann** [Light-City/CPlusPlusThings#125]
unique_ptr_U.cpp 

 60:  unique_ptr<shape> ptr2{ptr1}; // 由于带模板的移动构造函数引发编译器会默认生成拷贝构造

fix : 应该是带模板的构造函数不被编译器看做移动，从而不能自动触发删除拷贝构造函数的行为，因果关系不对把

 unique_ptr<shape> ptr2_2{std::move(ptr1)};    // 调用的是默认的移动构造,而不是带模板的移动构造 bitwise move

fix : 这里调用的就是带模板的移动构造

 ptr1 = ptr3;    // ok  根据形参先调用默认拷贝,再调用拷贝赋值

fix : 这里浅拷贝，segment fault怎么能写ok呢

 ptr3 = std::move(ptr1); // ok 根据形参先调用默认移动构造，而不是带参数的移动构造,再调用移动赋值

fix : 这里调用的模板构造函数

 unique_ptr<shape> ptr4(std::move(new circle));  // ok 调用带模板的移动构造

fix : 这里调用的默认构造函数

**Comment by Light-City** [comment]
1.fix : 应该是带模板的构造函数不被编译器看做移动，从而不能自动触发删除拷贝构造函数的行为，因果关系不对把

跟由于带模板的移动构造函数引发编译器会默认生成拷贝构造这句话没太大差别，不过这里表述的是间接关系。

2.调用的是默认的移动构造,而不是带模板的移动构造 bitwise move -> 感谢指正。
3.ptr1 = ptr3; // ok 根据形参先调用默认拷贝,再调用拷贝赋值

fix : 这里浅拷贝，segment fault怎么能写ok呢

这个你测试了嘛？我测试代码是ok的，并且确实浅拷贝，怎么会段错误？？？
4.这里跟你说的没冲突，这里我想表达的是先默认构造->默认移动->移动赋值，没有写默认构造。
5.done，ok  感谢纠正
