### ISSUE TITLE
基础部分struct

### ISSUE THREAD

**Issue by LuciusJay** [Light-City/CPlusPlusThings#128]
c++的struct是可以使用private修饰符的吧，为什么案例里标注为error呢？

**Comment by Light-City** [comment]
> c++的struct是可以使用private修饰符的吧，为什么案例里标注为error呢？

已删除，复制的时候漏了

**Comment by Light-City** [comment]
> c++的struct是可以使用private修饰符的吧，为什么案例里标注为error呢？

想起来了，有error表示 main调用私有成员报错，这里注释表示这个意思
