### ISSUE TITLE
十日狂练/day7/综合例题/重要.cpp中，重载赋值运算符=的成员函数是错误的

### ISSUE THREAD

**Issue by pbmenglq** [Light-City/CPlusPlusThings#130]
s3 = s1;
s1的长度比s3长，直接拷贝过去就数组越界了。
应该先给s3重新分配s1大小的内存。
String &operator=(const String &R){
            char *temp = sPtr;
            length = R.length;
            sPtr = new char[length + 1];
            strcpy(sPtr, R.sPtr);
            delete [] temp;
            return *this;
        }

**Comment by daidai21** [comment]
反过来短的赋值到长的也有问题
```cpp
    String s4, s5("abc");
    s5 = s4;
    cout << s4 << endl;
    cout << s5 << endl;
```

结果
```sh
>>> g++ ...
abc
abc
```

**Comment by nya9meows** [comment]
现在拷贝那一行变成了“strcpy(R.sPtr, sPtr);”是不是写反了

**Comment by Light-City** [comment]
> 现在拷贝那一行变成了“strcpy(R.sPtr, sPtr);”是不是写反了

已修复
