### ISSUE TITLE
十日狂练/day8/函数模板/模板特化.cpp中，并没有调用特化版本

### ISSUE THREAD

**Issue by pbmenglq** [Light-City/CPlusPlusThings#132]
程序第18行：    cout<<Max("xbv","xyce")<<endl;       
单步调试跟踪的时候，发现它并没有调用特化版本。我感觉原因是字符串常量的类型是字符常量数组，而特化版本接受的是字符指针，二者类型不同，数组名并不等于指针。
参考C++ Primer第625页，我觉得这样改好一点：

#include<iostream>
#include<cstring>

using namespace std;

template <typename T>
const T &Max(const T &a, const T &b) // 这里引用必须是对常量的引用，因为后面传递了字面值常量参数
{
    return  (a>b)?a:b;
}

//重载Max，处理字符串字面常量或者数组
template <size_t N, size_t M>
int Max(const char (&a) [N], const char (&b) [M]) // 注意括号，书上102页：有括号叫数组的引用；没括号叫引用的数组，是错误的，没有这种东西。
{
    return strcmp(a, b);
}

//特化版本：当传递的参数为字符指针的时候
//template <> 返回类型 函数名<特化的数据类型>(参数表){函数主体}
/*特例化版本的函数参数类型必须与一个先前声明的模板中对应的类型匹配！！！
  模板里面是 对常量T类型的引用，
  特化的T类型是 const char * ，即指向常字符类型的指针，
  那么特化版本的函数参数类型应该是 该指针常量类型的引用，
  即 const char * const & ，遵循从右往左结合的原则可以理解。
*/
template <>
const char * const & Max<const char *>(const char * const &a, const char * const &b)
{
    return (strcmp(a, b)>=0)?a:b;
}

int main(){
    float  c=5.1,d=3.2;
    cout<<"2,3的最大值是："<<Max(3,2)<<endl;   // 字面值常量只能绑定在const引用上，普通引用不行
    cout<<"c,d的最大值是："<<Max(c,d)<<endl;    // 这两个调用的是普通版本
    
    char str1[] = "xbv";
    char str2[] = "xyce";  
    if(Max(str1, str2) >= 0){ // 调用的是重载版本，数组名不是指针，所以不会去调用特化版本
        cout << str1 << endl;
    }
    else{
        cout << str2 << endl;
    }

    // 传递常量字符指针的情况
    const char *str3 = "xbv"; 
    const char *str4 = "xyce";
    cout << Max(str3, str4) << endl; // 这里调用的是特化版本

    cout<<Max("xbv","xyce")<<endl; // 调用的是重载版本            
    system("pause");
    return 0;
}
/*
① 当程序中同时存在模板和它的特化时，特化将被优先调用；
② 在同一个程序中，除了函数模板和它的特化外，还可以有同名的普通函数。其区别在于C++会对普通函数的调用实参进行隐式的类型转换，
但不会对模板函数及特化函数的参数进行任何形式的类型转换。
*/

**Comment by Light-City** [comment]
> 

感谢提建议，可以的话 可以直接提pr，谢谢
