### ISSUE TITLE
move.cpp文件中在win10的VS2019中报错：__hash_base不是模板

### ISSUE THREAD

**Issue by over-shine** [Light-City/CPlusPlusThings#134]

**Comment by daidai21** [comment]
```sh
➜  c++11 git:(master) g++ move.cpp -std=c++11 
move.cpp:191:42: error: no template named '__hash_base'
    struct hash<MyStringNoMove> : public __hash_base<size_t, MyStringNoMove> {
                                         ^
move.cpp:199:36: error: no template named '__hash_base'
    struct hash<MyString> : public __hash_base<size_t, MyString> {
                                   ^
2 errors generated.
➜  c++11 git:(master) brew list | grep libstdc++
```

应该是因为没有安装libstdc++这个库的原因，或者版本不对


libstdc++

https://github.com/gcc-mirror/gcc/tree/master/libstdc%2B%2B-v3

https://code.woboq.org/gcc/libstdc++-v3/include/bits/functional_hash.h.html#std::__hash_base

**Comment by Light-City** [comment]
> ```shell
> ➜  c++11 git:(master) g++ move.cpp -std=c++11 
> move.cpp:191:42: error: no template named '__hash_base'
>     struct hash<MyStringNoMove> : public __hash_base<size_t, MyStringNoMove> {
>                                          ^
> move.cpp:199:36: error: no template named '__hash_base'
>     struct hash<MyString> : public __hash_base<size_t, MyString> {
>                                    ^
> 2 errors generated.
> ➜  c++11 git:(master) brew list | grep libstdc++
> ```
> 
> 应该是因为没有安装libstdc++这个库的原因，或者版本不对
> 
> libstdc++
> 
> https://github.com/gcc-mirror/gcc/tree/master/libstdc%2B%2B-v3
> 
> https://code.woboq.org/gcc/libstdc++-v3/include/bits/functional_hash.h.html#std::__hash_base

正解
