### ISSUE TITLE
想问下十日实战的题目在哪里，点进去只有代码，和一个简单的文件名称。

### ISSUE THREAD

**Issue by AlieinApril** [Light-City/CPlusPlusThings#136]

**Comment by dxhlxr** [comment]
我也是刚看，标题估计就是题目吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月9日(周日) 下午4:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Light-City/CPlusPlusThings] 想问下十日实战的题目在哪里，点进去只有代码，和一个简单的文件名称。 (#136)

**Comment by Jihao-Hu** [comment]
没有题目的说明吗？

**Comment by Lemy28** [comment]
确实，关键是很多变量的命名也很迷惑，没题目好难看懂

**Comment by Lemy28** [comment]
您好，我是杜中华，您的邮件我已收到，我会在详细阅读后尽快回复您，谢谢。
