### ISSUE TITLE
一个 描述错误

### ISSUE THREAD

**Issue by CHxCOOH** [Light-City/CPlusPlusThings#14]
https://github.com/Light-City/CPlusPlusThings/blob/master/basic_content/vptr_vtable/vptr1.cpp
第89行
`cout<<"基类引用指向派生类实例"<<endl;`
应该是
`cout<<"基类引用指向基类实例"<<endl;`

**Comment by Light-City** [comment]
> https://github.com/Light-City/CPlusPlusThings/blob/master/basic_content/vptr_vtable/vptr1.cpp
> 第89行
> `cout<<"基类引用指向派生类实例"<<endl;`
> 应该是
> `cout<<"基类引用指向基类实例"<<endl;`

Thanks 已修正！
