### ISSUE TITLE
CPlusPlusThings/basic_content/const/README.MD中，最后一个例子（Apple）中方法有问题

### ISSUE THREAD

**Issue by sandilion** [Light-City/CPlusPlusThings#143]
int Apple::add(int num) const {
	take(num);
	return num;
}
这个方法，得写返回值，不然会编译报错的。

**Comment by Light-City** [comment]
> int Apple::add(int num) const { take(num); return num; } 这个方法，得写返回值，不然会编译报错的。

谢谢提醒，这里重点不是这个，当时写的比较随意！
