### ISSUE TITLE
新手小白求解：using那些事的using_global.cpp的主函数注释中的一句话，不知道自己的理解是否正确

### ISSUE THREAD

**Issue by mwm1c** [Light-City/CPlusPlusThings#149]
```c++
#include <iostream>
//#define isNs1 1
#define isGlobal 2
using namespace std;
void func()
{
    cout << "::func" << endl;
}

namespace ns1 {
    void func()
    {
        cout << "ns1::func" << endl;
    }
}

namespace ns2 {
#ifdef isNs1 
    using ns1::func;    // ns1中的函数
#elif isGlobal
    using ::func;       // 全局中的函数
#else
    void func()
    {
        cout << "other::func" << endl;
    }
#endif
}

int main()
{
/**
* 这就是为什么在c++中使用了cmath而不是math.h头文件
*/
    ns2::func(); // 会根据当前环境定义宏的不同来调用不同命名空间下的func()函数
    return 0;
}
```
这里作者在主函数中的注释说道：这就是为什么在c++中使用了cmath而不是math.h头文件，这句话的意思是说，<cmath>这个头文件是放在std这个命名空间下面的，所以得声明使用std这个命名空间才允许访问<cmath>，但<math.h>不用这样，是这个意思吗？

**Comment by 2417677728** [comment]
这个头文件不是在std命名空间中的，我觉得可能是因为cmath是使用类按照C++风格完成的头文件，里面使用了命名空间这种代码形式，更适合C++。而math.h纯粹就是C风格的文件内容替换吧。也就是实现结果一样，但是代码风格和扩展性不一样。(个人理解)

**Comment by JackDeng500** [comment]
cmath可以在全局下使用，但是会污染全局命名空间: 比如可以用一个编译器编译，但是不能用另一个编译器编译。而math.h不会
实际执行一下，不声明std也可以使用cmath，
可以看看alf的这篇回答
https://stackoverflow.com/questions/10694255/cmath-vs-math-h-and-similar-c-prefixed-vs-h-extension-headers
