### ISSUE TITLE
内容问题

### ISSUE THREAD

**Issue by Wulnut** [Light-City/CPlusPlusThings#15]
[这页(戳我)](https://github.com/Light-City/CPlusPlusThings/tree/master/practical_exercises/10_day_practice/day10)

- readme是乱码了吗

- 不知到是不是在这提issue

**Comment by Light-City** [comment]
那个是个标题，当时是再win系统搞得，后来迁移到linux下，所以乱码了，谢谢指出，已fix~

**Comment by Light-City** [comment]
> [这页(戳我)](https://github.com/Light-City/CPlusPlusThings/tree/master/practical_exercises/10_day_practice/day10)
> 
> * readme是乱码了吗
> * 不知到是不是在这提issue

那个是个标题，当时是再win系统搞得，后来迁移到linux下，所以乱码了，谢谢指出，已fix~
