### ISSUE TITLE
实战练习的题目

### ISSUE THREAD

**Issue by Cstardust** [Light-City/CPlusPlusThings#155]
输入输出运算符重载按理来讲返回的不应该是流的引用吗？我看C++Primer上返回类型的都是ostream&和istream&啊？

**Comment by Light-City** [comment]
返回加不加& 取决于后面是否操作，例如：cout << xxx << yy 就需要加 你只cout << xx就不需要了

**Comment by XuhuaHuang** [comment]
学校里教的大部分都是返回流的引用。不过后面是否操作这一点确实自己还没试过应用。
