### ISSUE TITLE
例题中遇到的一个问题

### ISSUE THREAD

**Issue by huangrunfeng** [Light-City/CPlusPlusThings#156]
day7/综合例题/重要.cpp
24行，strcpy的dst，src应该是写反了
strcpy(R.sPtr, sPtr);

**Comment by XuhuaHuang** [comment]
我也觉得是写反了。参考以下：`char * strcpy ( char * destination, const char * source );`
[C++ Reference](https://www.cplusplus.com/reference/cstring/strcpy/)
```C++
const String& operator=(const String& R)
    {
        length = R.length;
        strcpy(this->sPtr, R.sPtr);
        return *this;
    };  
```

**Comment by Light-City** [comment]
> 我也觉得是写反了。参考以下：`char * strcpy ( char * destination, const char * source );` [C++ Reference](https://www.cplusplus.com/reference/cstring/strcpy/)
> 
> ```c++
> const String& operator=(const String& R)
>     {
>         length = R.length;
>         strcpy(this->sPtr, R.sPtr);
>         return *this;
>     };  
> ```

已修复
