### ISSUE TITLE
毫无C++基础的能否根据这个项目来呢？

### ISSUE THREAD

**Issue by Donaghys** [Light-City/CPlusPlusThings#162]

**Comment by SuperSweetSong** [comment]
看了一下感觉这个是偏进阶的，推荐先学完C++基本语法再来看这个噢

**Comment by Donaghys** [comment]
您好，对于一个毫无C++基础的人想学习C++,请问有什么可以推荐的吗？

**Comment by Donaghys** [comment]
> 看了一下感觉这个是偏进阶的，推荐先学完C++基本语法再来看这个噢

您好，请问对于一个毫无C++基础的人来讲想学习C++，有什么推荐的吗？

**Comment by SuperSweetSong** [comment]
我之前也是在网上看别人推荐的学习路径，可以分享一下。b站“黑马程序员”的C++课程很不错，老师讲解思路很清晰，还有配套笔记。跟着敲代码全部看完就能基本入门，接着可以看"基于VSCode和CMake实现C/C++开发 | Linux篇"这个视频，也是非常不错，然后就可以在github上找一些项目跟着学习了。
我个人的学习路径是这样的，目前感觉还不错，不知道其他人有没有更好的补充
