### ISSUE TITLE
关于this指针是A * const 的疑惑

### ISSUE THREAD

**Issue by 2017zhangyuxuan** [Light-City/CPlusPlusThings#165]
![image](https://user-images.githubusercontent.com/43541108/133257479-804973e4-4a44-42ea-8dc4-3dd941524162.png)
![image](https://user-images.githubusercontent.com/43541108/133257591-84816ab4-1dfa-43a8-aab4-4ee46d8849d8.png)
用的是相同代码，C11版本，显示的是Person *

**Comment by 2017zhangyuxuan** [comment]
但是 this 指针仍然无法进行赋值操作

**Comment by Light-City** [comment]
> 但是 this 指针仍然无法进行赋值操作

检查g++版本
