### ISSUE TITLE
关于sizeof 的疑惑

### ISSUE THREAD

**Issue by 2017zhangyuxuan** [Light-City/CPlusPlusThings#166]
![image](https://user-images.githubusercontent.com/43541108/133358678-98d3aae2-1f74-41d3-a636-986a1393b963.png)
class C 本身也有新的虚函数，不应该有自己的虚函数指针vptr吗？ 所以应该有3个虚函数指针？
另外，在网上看到，如果是虚继承的话，还会有指向“虚基类表”的指针，这里有两个虚继承，所以还有2个虚继承的指针？

**Comment by AlieZ22** [comment]
轩哥hhhh
继承的时候，子类和基类会共享虚函数表，而多继承时，**派生类有多少个虚基类就有多少个虚函数表的指针**，所以class C就只有两个指向虚表的指针。
或者用**sizeof(派生类)=所有基类的存储空间+派生类中非static数据成员的空间**，也可以得出来是16。
下面解释一下：
每当创建一个包含虚函数的类或者从包含虚函数的类派生一个类时，编译器就会为这个类创建一个虚函数表，保存该类**所有**虚函数的地址（子类和基类的虚函数，在单继承时会共享虚表，就只有一个虚指针。可以C单虚继承A试一下，结果应该是8）。
比如这个类C，其存储空间应该是：
<img width="389" alt="x" src="https://user-images.githubusercontent.com/34917442/133721874-63814b6e-dad5-4677-8a73-e386bb6bc1d8.png">
有两个虚指针，且C中没有其他非static成员，在64位系统上，sizeof就是16bytes
