### ISSUE TITLE
Boy is not a member of Person

### ISSUE THREAD

**Issue by parwjs** [Light-City/CPlusPlusThings#167]
在这个this的章节，初始化Person对象的时候，Person p("zhangsan",20,Person::Boy);

**Comment by XuhuaHuang** [comment]
您好，请问可以放一下源码链接吗，谢谢。

**Comment by XuhuaHuang** [comment]
> 在这个this的章节，初始化Person对象的时候，Person p("zhangsan",20,Person::Boy);

您好，请问可以放一下源码链接吗，谢谢。
