### ISSUE TITLE
关于cosnt中对类的介绍有误或存在理解争议

### ISSUE THREAD

**Issue by zzethld** [Light-City/CPlusPlusThings#169]
在int Apple::getCount() const{}中，add出错并不是因为add非const修饰，如果就直接copy代码下来编译，出错原因是未给add添加参数。（或者说是我理解有问题？博主的意思是如果写一个非const的add是不能调用？）而且我认为getCount这个例子的结论应该是const成员函数只能调用const成员函数，而非const对象。
`int Apple::getCount() const
{
    take(1);
    add(); //err 
    return apple_number;
}`

**Comment by Light-City** [comment]
> 在int Apple::getCount() const{}中，add出错并不是因为add非const修饰，如果就直接copy代码下来编译，出错原因是未给add添加参数。（或者说是我理解有问题？博主的意思是如果写一个非const的add是不能调用？）而且我认为getCount这个例子的结论应该是const成员函数只能调用const成员函数，而非const对象。 `int Apple::getCount() const { take(1); add(); //err return apple_number; }`

是的
