### ISSUE TITLE
const那些事的问题

### ISSUE THREAD

**Issue by GITdenny** [Light-City/CPlusPlusThings#17]
再介绍常指针和指向常量的指针那里，有些含糊不清，半天抓不住要领，应该直接说明实质，如：常指针 是指针指向的位置不能改变，也就是指针的指只能赋值一次。指向常量的指针 是指指针指向的对象不能改变，也就是说不能通过这个指针来改变指向对象的指，而指针自身的指向是可以改变的。

**Comment by Light-City** [comment]
> 再介绍常指针和指向常量的指针那里，有些含糊不清，半天抓不住要领，应该直接说明实质，如：常指针 是指针指向的位置不能改变，也就是指针的指只能赋值一次。指向常量的指针 是指指针指向的对象不能改变，也就是说不能通过这个指针来改变指向对象的指，而指针自身的指向是可以改变的。

感谢提意见，当时写const的时候，是想写的更详细，写的就有点多了。
