### ISSUE TITLE
decltype推导数组类型

### ISSUE THREAD

**Issue by 2017zhangyuxuan** [Light-City/CPlusPlusThings#170]
![image](https://user-images.githubusercontent.com/43541108/135010927-01ad736a-2a9d-4ec6-b6a2-e0d371468c7c.png)
这里的推导是不是错了，应该是推导成int[5] 数组类型吧。
对应地址「基础进阶」-> 「devltype那些事」-> 「2.判别规则」 
https://light-city.club/sc/basic_content/decltype/

**Comment by Light-City** [comment]
> ![image](https://user-images.githubusercontent.com/43541108/135010927-01ad736a-2a9d-4ec6-b6a2-e0d371468c7c.png) 这里的推导是不是错了，应该是推导成int[5] 数组类型吧。 对应地址「基础进阶」-> 「devltype那些事」-> 「2.判别规则」 https://light-city.club/sc/basic_content/decltype/

你说的没错
