### ISSUE TITLE
 const章节中的问题

### ISSUE THREAD

**Issue by ChunChunLiGong** [Light-City/CPlusPlusThings#171]
![image](https://user-images.githubusercontent.com/92280805/136720314-8a6f0fec-fd14-4541-86c6-87357f3791e6.png)
![image](https://user-images.githubusercontent.com/92280805/136720363-2fa85220-2d35-4da2-91c1-4145bc6b17b3.png)

> **这个add出错是因为没有传参数吧，传参之后是可以正常运行的。**

![image](https://user-images.githubusercontent.com/92280805/136720391-1131ed69-6d4a-4d07-8a04-5fa4ba43b769.png)
![image](https://user-images.githubusercontent.com/92280805/136720396-93143f75-0d99-4415-8f60-404e2b80a588.png)

> **const优先调用const，非const优先调用非const**

**Comment by Light-City** [comment]
> ![image](https://user-images.githubusercontent.com/92280805/136720314-8a6f0fec-fd14-4541-86c6-87357f3791e6.png) ![image](https://user-images.githubusercontent.com/92280805/136720363-2fa85220-2d35-4da2-91c1-4145bc6b17b3.png)
> 
> > **这个add出错是因为没有传参数吧，传参之后是可以正常运行的。**
> 
> ![image](https://user-images.githubusercontent.com/92280805/136720391-1131ed69-6d4a-4d07-8a04-5fa4ba43b769.png) ![image](https://user-images.githubusercontent.com/92280805/136720396-93143f75-0d99-4415-8f60-404e2b80a588.png)
> 
> > **const优先调用const，非const优先调用非const**
正解
