### ISSUE TITLE
第一节const修饰的问题

### ISSUE THREAD

**Issue by APMMaster** [Light-City/CPlusPlusThings#172]
int Apple::add(int num){
    take(num);
}
int Apple::add(int num) const{
    take(num);
}

这里，const修饰的成员函数与没有const修饰的成员函数内容完全相同，起不到区分作用，建议将第二个成员函数的
 take(num);
改为
 take(num+1);

**Comment by hahaha1014** [comment]
add函数没有return返回值，是不是应该在take(num);之后添加return语句

**Comment by hugh-tong** [comment]
> 

我觉得也是 不return应该会报错吧

**Comment by Light-City** [comment]
> int Apple::add(int num){ take(num); } int Apple::add(int num) const{ take(num); }
> 
> 这里，const修饰的成员函数与没有const修饰的成员函数内容完全相同，起不到区分作用，建议将第二个成员函数的 take(num); 改为 take(num+1);

已修复
