### ISSUE TITLE
const章节

### ISSUE THREAD

**Issue by String10** [Light-City/CPlusPlusThings#173]
![image](https://user-images.githubusercontent.com/69832835/138869877-31bb18fd-110c-4c80-88f6-05bea3933d7d.png)
这里的声明
```c++
int ext
```
少了一个分号。

**Comment by XuhuaHuang** [comment]
This issue has been resolved. Click [here](https://github.com/Light-City/CPlusPlusThings/blob/master/basic_content/const/extern_const/file2.cpp) to see the change. Please close this issue.
