### ISSUE TITLE
CPlusPlusThings/basic_content/func_pointer/func_pointer.cpp

### ISSUE THREAD

**Issue by HonorableLeon** [Light-City/CPlusPlusThings#174]
CPlusPlusThings/basic_content/func_pointer/func_pointer.cpp 第 13行注释
“指向返回值和参数都是空的函数的指针！”应为 “指向返回值是空、参数是int的函数的指针！”
原文12行到15行如下
/**
 * @brief 定义了一个变量pFun，这个变量是个指针，指向返回值和参数都是空的函数的指针！
 */
void (*pFun)(int);

**Comment by XuhuaHuang** [comment]
你说的是对的，自己改一下然后开一个pull request吧。很细心！加油！

**Comment by Light-City** [comment]
> 

已修复
