### ISSUE TITLE
day5/构造函数与析构函数/派生类给基类传递参数.cpp

### ISSUE THREAD

**Issue by nya9meows** [Light-City/CPlusPlusThings#175]
基类构造函数不按照写的执行，虽然会给x和y 分别赋值a和b，但并不执行cout。
修改构造函数为y=a;x=b;之后仍然按照x=a;y=b;执行。把Point改成Point1后恢复正常。同一目录下有另一个c++文件里也有名叫Point的类，但里面声明的是private而不是protected，请问这在编译时也会算作同一个类么？
class Point{
protected:
    int x,y;
public:
    Point(int a,int b=0) {
        x=a;  y=b;
        cout<<"constructing point("<<x<<","<<y<<")"<<endl;
    }
};

**Comment by XuhuaHuang** [comment]
如果你使用编译器单独编译的话，编译器是看不到位于别的文件中的类的。不执行cout会不会是namespace pollution？
试试把`using namespace std;` 去掉，再加上所有缺失的`std::`再试一次吧。

**Comment by nya9meows** [comment]
> 如果你使用编译器单独编译的话，编译器是看不到位于别的文件中的类的。不执行cout会不会是namespace pollution？ 试试把`using namespace std;` 去掉，再加上所有缺失的`std::`再试一次吧。

去掉namespace还是不行。。然后它确实读到了其他文件的类，因为当我在其他文件里的同名类的构造函数里加了个cout以后，它确实显示出了那个cout里面的东西
