### ISSUE TITLE
day7/[]与()例题/example1.cpp

### ISSUE THREAD

**Issue by nya9meows** [Light-City/CPlusPlusThings#176]
将int operator[](char* cp)修改成int operator[](const char* cp)，或者将int b = obj["abcd"];修改为int b = obj[const_cast<char*>("abcd")];否则就报错，说"a value of type const char * cannot be used to initialize an entity of type char * "
查了下好像C++现在把“xxxx”返回类型定义成了const char * ? (C里面还是定义成char*)不知道是不是只有我有这个问题，用的是visual studio2019

**Comment by Light-City** [comment]
这里都是可以的
