### ISSUE TITLE
惯用法/RAII中，文件读取时使用!file_handle.eof()判断读取结束的问题

### ISSUE THREAD

**Issue by taiwei-t** [Light-City/CPlusPlusThings#179]
读完之后还要再读一次才会读到EOF标志，因此最后一行的内容会push两次，导致读取的行数多1；
可以将判断改为file_handle.peek() != EOF

**Comment by Light-City** [comment]
> 读完之后还要再读一次才会读到EOF标志，因此最后一行的内容会push两次，导致读取的行数多1； 可以将判断改为file_handle.peek() != EOF

非常感谢这个建议！
