### ISSUE TITLE
基础进阶需要动手重新敲一遍代码吗？

### ISSUE THREAD

**Issue by hahaha1014** [Light-City/CPlusPlusThings#180]
感觉自己敲一遍代码有点费时，但是不动手写的话感觉学不进去。不知道大家是怎么学习基础进阶这一块内容的？

**Comment by XuhuaHuang** [comment]
如果是自己不了解的，建议还是自己动手敲一遍；如果是自己能看懂，也觉得自己能写出来的就别敲了。自己写一个Markdown笔记，是不是回看一下更实用。

**Comment by Light-City** [comment]
> 感觉自己敲一遍代码有点费时，但是不动手写的话感觉学不进去。不知道大家是怎么学习基础进阶这一块内容的？

自己都没写过怎么学得会 动起来～

**Comment by hahaha1014** [comment]
> > 感觉自己敲一遍代码有点费时，但是不动手写的话感觉学不进去。不知道大家是怎么学习基础进阶这一块内容的？
> 
> 自己都没写过怎么学得会 动起来～

被作者回复了好兴奋hhh。基础进阶部分我都是手敲一遍代码，根据笔记还有其他资料总结了个人笔记。打算这个寒假把实战系列以及STL过一遍，希望早日精通c++。

**Comment by Crazy-A2** [comment]
精通？我佩服你是真的勇士



| |
qwe453931370
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月23日 10:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [Light-City/CPlusPlusThings] 基础进阶需要动手重新敲一遍代码吗？ (Issue #180) |

感觉自己敲一遍代码有点费时，但是不动手写的话感觉学不进去。不知道大家是怎么学习基础进阶这一块内容的？

自己都没写过怎么学得会 动起来～

被作者回复了好兴奋hhh。基础进阶部分我都是手敲一遍代码，根据笔记还有其他资料总结了个人笔记。打算这个寒假把实战系列以及STL过一遍，希望早日精通c++。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
