### ISSUE TITLE
示例报错：允许把非const对象的地址赋给指向const对象的指针。

### ISSUE THREAD

**Issue by OxfordStreet** [Light-City/CPlusPlusThings#191]
在basic_content/const那些事儿中：
![image](https://user-images.githubusercontent.com/32759302/147846975-d858033b-09d5-4375-aadf-6fd2dddb5bf0.png)
在cmder中编辑并执行代码：
![image](https://user-images.githubusercontent.com/32759302/147847036-a1b8c3a0-ae7a-461a-adc9-5f2fc03cc359.png)
报错信息如下：
` error: 'ptr' does not name a type`
` ptr = &val; //ok`
 `^~~`
这有可能是什么问题导致的？

**Comment by Light-City** [comment]
> 在basic_content/const那些事儿中： ![image](https://user-images.githubusercontent.com/32759302/147846975-d858033b-09d5-4375-aadf-6fd2dddb5bf0.png) 在cmder中编辑并执行代码： ![image](https://user-images.githubusercontent.com/32759302/147847036-a1b8c3a0-ae7a-461a-adc9-5f2fc03cc359.png) 报错信息如下： ` error: 'ptr' does not name a type` ` ptr = &val; //ok` `^~~` 这有可能是什么问题导致的？

没有定义类型
