### ISSUE TITLE
继承命名冲突是可以通过添加类名的域解决的

### ISSUE THREAD

**Issue by dujingning** [Light-City/CPlusPlusThings#192]
CPlusPlusThings/practical_exercises/10_day_practice/day5/虚拟继承/

多继承同名成员函数如下：
`#include<iostream>
using namespace std;
class A {
public:
        void vf() {
                cout<<"I come from class A"<<endl;      }
};
class B: public A{};
class C: public A{};
class D: public B, public C{};

int main()
{
        D d;
        d.B::vf ();     // 正确 √
        d.C::vf ();     // 正确 √
    return 0;
}
~
`
同名变量如下：
`#include<iostream>
using namespace std;
class B
{
public:
        char a;
};

class C
{
public:
        double a;
};

class D:public B,public C
{
public:
};

int main()
{
    D d;
    d.B::a = 'a';     // 正确 √
    d.C::a = 666.66;      // 正确 √
    cout << d.B::a << endl;
    cout << d.C::a << endl;
    return 0;
}
`

**Comment by Light-City** [comment]
> CPlusPlusThings/practical_exercises/10_day_practice/day5/虚拟继承/
> 
> 多继承同名成员函数如下： `#include using namespace std; class A { public: void vf() { cout<<"I come from class A"<<endl; } }; class B: public A{}; class C: public A{}; class D: public B, public C{};
> 
> int main() { D d; d.B::vf (); // 正确 √ d.C::vf (); // 正确 √ return 0; } ~ `同名变量如下：`#include using namespace std; class B { public: char a; };
> 
> class C { public: double a; };
> 
> class D:public B,public C { public: };
> 
> int main() { D d; d.B::a = 'a'; // 正确 √ d.C::a = 666.66; // 正确 √ cout << d.B::a << endl; cout << d.C::a << endl; return 0; } `

you are right
