### ISSUE TITLE
sizeof 章节存在几处内存对齐问题

### ISSUE THREAD

**Issue by danielljc** [Light-City/CPlusPlusThings#195]
1. `class B:A { public: short a; long b; };`
有效对齐值为：4
因此short a占用4 Bytes，long b占用4 Bytes，最终结果为sizeof(B) = 16。

2. `class C : virtual public A, virtual public B {
public:
    virtual void fun3()
    {}
};`
C共享A、B的虚函数表，有2个vptr；C同时指向虚基类，还有有2个vptr，共4个vptr，结果为sizeof(C) = 32。

**Comment by Light-City** [comment]
> 1. `class B:A { public: short a; long b; };`
>    有效对齐值为：4
>    因此short a占用4 Bytes，long b占用4 Bytes，最终结果为sizeof(B) = 16。
> 2. `class C : virtual public A, virtual public B { public: virtual void fun3() {} };`
>    C共享A、B的虚函数表，有2个vptr；C同时指向虚基类，还有有2个vptr，共4个vptr，结果为sizeof(C) = 32。

不要盲目下结论，看我用的系统再说，32位、64位、linux与win的结果都是不一样的。。。

**Comment by danielljc** [comment]
sorry

**Comment by danielljc** [comment]
不好意思，刚刚注意到您系统是linux，但是编译器架构好像没有给出，我这样推断你看是否正确：
`class A
{
    public:
        char a;
        int b;
};`
原文中给出的结果是sizeof(A) = 8，也就是说编译器是32位的（无论32bit还是64bit的win，int都是4字节的，而linux中有区分），那么
‘class B:A
{
    public:
        short a;
        long b;
};’
此时对齐系数是4，B的有效对齐值为4，假设起始地址为0，那么A::a占用0~3，A::b占用4~7，B::a占用8~11，B::b占用12~15，结果不应该是16字节吗？

对于问题2，由于原文中sizeof(A)和sizeof(B)都是8字节，那么sizeof(C)除了2个vptr外还得维护2个指针，必然大于16字节。

小弟不得其解，望大佬不吝赐教。
