### ISSUE TITLE
[const那点事]不显式声明变量也可以正常访问

### ISSUE THREAD

**Issue by sunyuhan19981208** [Light-City/CPlusPlusThings#199]
file2.cpp

```c++
const int ext = 20;
```

file1.cpp

```c++
#include<iostream>
#include"file2.cpp"

extern const int ext;
int main(){
	std::cout<< ext <<std::endl;
}
```

output

```
20
[Finished in 856ms]
```

g++环境

Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: arm64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

编译选项

{
    "cmd" : ["/usr/bin/g++ $file_name -std=c++11 -o ${file_base_name} && ./${file_base_name}"],
    "selector" : "source.c, source.c++",
    "shell": true,
    "working_dir" : "$file_path"
}

**Comment by Light-City** [comment]
这，，正常我这边是报错了的

**Comment by Light-City** [comment]
> file2.cpp
> 
> ```c++
> const int ext = 20;
> ```
> 
> file1.cpp
> 
> ```c++
> #include<iostream>
> #include"file2.cpp"
> 
> extern const int ext;
> int main(){
> 	std::cout<< ext <<std::endl;
> }
> ```
> 
> output
> 
> ```
> 20
> [Finished in 856ms]
> ```
> 
> g++环境
> 
> Apple clang version 12.0.5 (clang-1205.0.22.11) Target: arm64-apple-darwin20.6.0 Thread model: posix InstalledDir: /Library/Developer/CommandLineTools/usr/bin
> 
> 编译选项
> 
> { "cmd" : ["/usr/bin/g++ $file_name -std=c++11 -o ${file_base_name} && ./${file_base_name}"], "selector" : "source.c, source.c++", "shell": true, "working_dir" : "$file_path" }

诡异

**Comment by XuhuaHuang** [comment]
我觉得是不应该有`#include "file2.cpp“`的；因为既然需要`extern`，据说明这个变量在本文件中不存在；现在预处理器把整个“file2.cpp” 复制过来了，我的猜想是被复制的这个变量把原本应该有的外部链接（external linkage）覆盖掉了。
而且C++标准里好像提过不应该include 一个cpp文件，"as this is a window to undefined behavior".

**Comment by Light-City** [comment]
> 我觉得是不应该有`#include "file2.cpp“`的；因为既然需要`extern`，据说明这个变量在本文件中不存在；现在预处理器把整个“file2.cpp” 复制过来了，我的猜想是被复制的这个变量把原本应该有的外部链接（external linkage）覆盖掉了。 而且C++标准里好像提过不应该include 一个cpp文件，"as this is a window to undefined behavior".

难怪没发现问题，是这个原因！
