### ISSUE TITLE
找到几个bug

### ISSUE THREAD

**Issue by syjml** [Light-City/CPlusPlusThings#20]
![微信图片_20200526105131](https://user-images.githubusercontent.com/8069021/82855809-e65f1080-9f3e-11ea-8b92-69a0e5b905a9.png)

https://light-city.club/sc/basic_content/vptr_vtable/
最派生函数，应该是笔误。

![微信图片_20200526105549](https://user-images.githubusercontent.com/8069021/82855995-7a30dc80-9f3f-11ea-99a5-6cc33c5434ed.png)
https://light-city.club/sc/basic_content/extern/
符号，而不是符时

![微信图片_20200526105724](https://user-images.githubusercontent.com/8069021/82856090-b106f280-9f3f-11ea-828f-b034b85ff9e7.png)
https://light-city.club/sc/basic_content/pointer_refer/
建议不要用“鲁棒性”这个糟糕的翻译，改为用健壮性，稳健性

**Comment by hmsjy2017** [comment]
> 鲁棒性

还不如叫『稳定性』

**Comment by Light-City** [comment]
已解决~
