### ISSUE TITLE
[const那点事]第七小节举的类中使用const的第二个例子

### ISSUE THREAD

**Issue by sunyuhan19981208** [Light-City/CPlusPlusThings#200]
上面getCount()方法中调用了一个add方法，而add方法并非const修饰，所以运行报错。也就是说const**对象**只能访问const成员函数。

而add方法又调用了const修饰的take方法，证明了非const**对象**可以访问任意的成员函数,包括const成员函数。

上述这两个地方是否都应该是const成员函数而不是const对象

**Comment by Light-City** [comment]
你说的对 const成员函数

**Comment by Light-City** [comment]
> 上面getCount()方法中调用了一个add方法，而add方法并非const修饰，所以运行报错。也就是说const**对象**只能访问const成员函数。
> 
> 而add方法又调用了const修饰的take方法，证明了非const**对象**可以访问任意的成员函数,包括const成员函数。
> 
> 上述这两个地方是否都应该是const成员函数而不是const对象

const成员函数

**Comment by Light-City** [comment]
> 上面getCount()方法中调用了一个add方法，而add方法并非const修饰，所以运行报错。也就是说const**对象**只能访问const成员函数。
> 
> 而add方法又调用了const修饰的take方法，证明了非const**对象**可以访问任意的成员函数,包括const成员函数。
> 
> 上述这两个地方是否都应该是const成员函数而不是const对象

这里的话确实是非const对象，可以看一下main函数
