### ISSUE TITLE
[sizeof那点事] 原则4的C类大小为什么不是16，而是12？？

### ISSUE THREAD

**Issue by mouzougaai** [Light-City/CPlusPlusThings#204]
原则4，为什么C大小为12？A的大小是8，char a大小内存对齐应该是8吧，C大小应该是16。我这样想错在哪了?

**Comment by CYP12138** [comment]
应该把A的成员拆开看，char为1，int为4，所以是1+（3）+4+1+（3）=12，（）为字节补齐。

**Comment by Light-City** [comment]
> 应该把A的成员拆开看，char为1，int为4，所以是1+（3）+4+1+（3）=12，（）为字节补齐。

　正确！
