### ISSUE TITLE
构造函数调用次序内存泄漏

### ISSUE THREAD

**Issue by Sunyouteng** [Light-City/CPlusPlusThings#209]
https://github.com/Light-City/CPlusPlusThings/blob/696b01a42c561de02f217d7404b5b4ccdc5b58c9/practical_exercises/10_day_practice/day5/%E6%9E%84%E9%80%A0%E5%87%BD%E6%95%B0%E4%B8%8E%E6%9E%90%E6%9E%84%E5%87%BD%E6%95%B0/%E6%9E%84%E9%80%A0%E5%87%BD%E6%95%B0%E8%B0%83%E7%94%A8%E6%AC%A1%E5%BA%8F.cpp#L31
这里不知道是否存在内存泄漏，D的析构并没有手动释放a?

**Comment by Light-City** [comment]
> 

demo示例 没有手动释放 这里可能后面要补充
