### ISSUE TITLE
关于举的那个const extern的例子

### ISSUE THREAD

**Issue by Owen1257173018** [Light-City/CPlusPlusThings#212]
无论我怎么编译都是错的，发现在file1.cpp里面加上#include"file2.cpp"就可以了，所以到底要不要加？我用的是arm下的clang

**Comment by XuhuaHuang** [comment]
> 无论我怎么编译都是错的，发现在file1.cpp里面加上#include"file2.cpp"就可以了，所以到底要不要加？我用的是arm下的clang

您好，

我以前解释过这个issue，不过我不介意再解释一遍。

`#include`是把一个文件复制过来本文件的一个编译器宏指令，所以在这里编译器会把`file2.cpp`里的内容完完整整的复制过来，通常来说不应该这么做，因为这很容易导致未定义行为，包括C++标准，Effective C++ 书本都是这么建议的。如果`file2.cpp`里面也有一个main函数的话，这样文件里就会有两个主函数入口了。

这是一个比较简单的，关于`extern`的讨论，所以在这里没有大问题。

如果可以，请截图一下编译错误，大家一起来想想办法，谢谢。
