### ISSUE TITLE
理解沟通

### ISSUE THREAD

**Issue by nieyan** [Light-City/CPlusPlusThings#217]
https://github.com/Light-City/CPlusPlusThings/blob/9f58fef2ce23ed788dc3f6151446d7bc47194269/basic_content/vptr_vtable/vptr1.cpp#L93

这里注释是否应改为 ：基类引用指向派生类实例并调用虚函数

**Comment by BlingDan** [comment]
萌新也有这个疑问，哪位大佬能讲解下吗
