### ISSUE TITLE
在宏这一章，2.4定义单一的函数块来完成复杂的操作

### ISSUE THREAD

**Issue by 1838641320** [Light-City/CPlusPlusThings#222]
这里则不需要`do{}while(0);`
直接套上大括号即可
```cpp
void solve(){
	int x=3;
	{
		int x=345;
		cout<<x<<endl;
	}
	cout<<x<<endl;
}
```

**Comment by XuhuaHuang** [comment]
> 这里则不需要`do{}while(0);` 直接套上大括号即可
> 
> ```c++
> void solve(){
> 	int x=3;
> 	{
> 		int x=345;
> 		cout<<x<<endl;
> 	}
> 	cout<<x<<endl;
> }
> ```

新开了一个scope，从变量可见性的角度来说确实和`do{}while(0)`语句块效果一致。我觉得这个issue可以关了。
或者issue作者提一个pr加在src或者REAMDME里面吧。
