### ISSUE TITLE
目前就看了一章v_table/v_func的，感觉太不严谨了

### ISSUE THREAD

**Issue by HWZen** [Light-City/CPlusPlusThings#225]
https://github.com/Light-City/CPlusPlusThings/blob/9f58fef2ce23ed788dc3f6151446d7bc47194269/basic_content/vptr_vtable/vptr1.cpp#L69
不是所有x64编译器的unsignal long都是8位，像我MSVC 19.32 unsignal long就是四位
我更推荐的写法是：
``` c++
void* vptr_addr = *(void **)obj;
```
<br>
<br>
<br>

https://github.com/Light-City/CPlusPlusThings/blob/9f58fef2ce23ed788dc3f6151446d7bc47194269/basic_content/vptr_vtable/vptr1.cpp#L99
https://github.com/Light-City/CPlusPlusThings/blob/9f58fef2ce23ed788dc3f6151446d7bc47194269/basic_content/vptr_vtable/vptr1.cpp#L101
这两行更是重量级，竟敢让非静态成员函数无参运行？？
虽然你的成员函数没有调用this，不会出什么问题，但建议还是加上this形参：
``` c++
using Fun = void(*)(Base *)
Base *pt = new Derived();
Fun f1 = getAddr(pt, 0);
(*f1)(pt);
```

**Comment by Light-City** [comment]
> https://github.com/Light-City/CPlusPlusThings/blob/9f58fef2ce23ed788dc3f6151446d7bc47194269/basic_content/vptr_vtable/vptr1.cpp#L69
> 
> 
> 不是所有x64编译器的unsignal long都是8位，像我MSVC 19.32 unsignal long就是四位
> 我更推荐的写法是：
> ```c++
> void* vptr_addr = *(void **)obj;
> ```
> 
> 
> 
> 
> https://github.com/Light-City/CPlusPlusThings/blob/9f58fef2ce23ed788dc3f6151446d7bc47194269/basic_content/vptr_vtable/vptr1.cpp#L99
> 
> 
> https://github.com/Light-City/CPlusPlusThings/blob/9f58fef2ce23ed788dc3f6151446d7bc47194269/basic_content/vptr_vtable/vptr1.cpp#L101
> 
> 
> 这两行更是重量级，竟敢让非静态成员函数无参运行？？
> 虽然你的成员函数没有调用this，不会出什么问题，但建议还是加上this形参：
> ```c++
> using Fun = void(*)(Base *)
> Base *pt = new Derived();
> Fun f1 = getAddr(pt, 0);
> (*f1)(pt);
> ```

注意看一开头提示的系统
