### ISSUE TITLE
在vptr_vtable 这一章

### ISSUE THREAD

**Issue by hr2894235132** [Light-City/CPlusPlusThings#228]
在手动查找vtable中我的运行结果和您给的不太一样。可以帮我解答一下嘛，非常感谢！！！
![image](https://user-images.githubusercontent.com/86639226/178505382-6ddb341f-4341-4b05-b13f-84a6f98b0cfa.png)
![image](https://user-images.githubusercontent.com/86639226/178505647-be166c2b-084c-4137-b9af-0e2e654b4e34.png)
我的f2地址为null。

**Comment by XuhuaHuang** [comment]
我看您这个背景，是在用CLion吗？我以前用CLion时就发现它在使用debugger时输出和release不一样，推荐在terminal里手动编译，再看看结果。

**Comment by hr2894235132** [comment]
> 我看您这个背景，是在用CLion吗？我以前用CLion时就发现它在使用debugger时输出和release不一样，推荐在terminal里手动编译，再看看结果。

对，是clion，那我用终端试试，感谢您的回复！
