### ISSUE TITLE
一元运算符一章中计数器前后自增.cpp

### ISSUE THREAD

**Issue by Gavin1129** [Light-City/CPlusPlusThings#240]
Postfix version 和 Prefix version 的实现是不是有问题？

Counter Counter::operator++(int){
n++;
return *this;
}

不也是返回自增后的值吗？

**Comment by Light-City** [comment]
> Postfix version 和 Prefix version 的实现是不是有问题？
> 
> Counter Counter::operator++(int){ n++; return *this; }
> 
> 不也是返回自增后的值吗？

yes, has beened fixed.
