### ISSUE TITLE
Function 

### ISSUE THREAD

**Issue by Avidcord4482811** [Light-City/CPlusPlusThings#244]
Function is complicated to me please someone explain it to me

**Comment by XuhuaHuang** [comment]
> Function is complicated to me please someone explain it to me

Greetings,
the community is more than happy to help and support! please come up with a more specific question or the topic you want to talk about for better assistance ;)
Also, a little of background introduction might help; e.g. what you know so far, what kind of programming experience you have gained so far e.t.c.
It's really hard to determine the individual definition of "complicated"; Thank you for understanding.
