### ISSUE TITLE
关于sizeof中原则6虚继承

### ISSUE THREAD

**Issue by lihuayan** [Light-City/CPlusPlusThings#246]
我将代码copy运行，得到的A、B、C的大小分别为8、8、32（64位），按照我的理解来看应该是8、8、24。但文中确实8、8、16

**Comment by XuhuaHuang** [comment]
![image](https://user-images.githubusercontent.com/71360506/205473522-9e5b68c6-c088-4f1a-acaa-7c0685799a0e.png)
![image](https://user-images.githubusercontent.com/71360506/205473533-12ecc971-14a5-4d99-899e-e7ec101ccf82.png)
这是我跑的结果；有点匪夷所思，期待作者解答。

**Comment by XuhuaHuang** [comment]
补充说明，为了证实不是被编译器优化，我在`C`中实现了`fun()`和`fun2()`的override版本，结果与上图相同。

**Comment by LVooo** [comment]
这个是和编译器相关的。  
在Windows下，如果是虚继承，那么子类中会增加一个虚类指针，也就是**vptr**。如果子类中又包含自己的虚函数，那么又会创建一个新的虚函数表指针**vfptr**。  
而在gcc环境下，这两个指针是被合并了的。
