### ISSUE TITLE
const 章节表述疑问

### ISSUE THREAD

**Issue by Knight-ZXW** [Light-City/CPlusPlusThings#248]
![image](https://user-images.githubusercontent.com/11730925/208966197-043e5b0f-91d9-4b03-81ea-95f5efe37622.png)

对于此项，c++11不能进行声明并初始化，也就是上述使用方法。

这里实际是想表达c++11以下不能 直接声明并初始化 类静态成员变量吗？

**Comment by Light-City** [comment]
是的
