### ISSUE TITLE
链接挂了

### ISSUE THREAD

**Issue by c-cpp-a** [Light-City/CPlusPlusThings#251]
[图片](https://cdn.luogu.com.cn/upload/image_hosting/tgscjkvq.png)中红色箭头所指的链接挂了，[加载情况](https://cdn.luogu.com.cn/upload/image_hosting/4jpy7koz.png)。建议更新/强化链接

**Comment by c-cpp-a** [comment]
走了一圈发现大多数图片链接都挂了

**Comment by Light-City** [comment]
> [图片](https://cdn.luogu.com.cn/upload/image_hosting/tgscjkvq.png)中红色箭头所指的链接挂了，[加载情况](https://cdn.luogu.com.cn/upload/image_hosting/4jpy7koz.png)。建议更新/强化链接

同 issue https://github.com/Light-City/CPlusPlusThings/issues/197
