### ISSUE TITLE
调整 cpp 文件格式为 utf8, 解决 Mac 下 vscode 打开乱码问题

### ISSUE THREAD

**Issue by tracyxiong1** [Light-City/CPlusPlusThings#253]
`practical_exercises` 中有大量 `GBK` 编码文件，由于在 Mac vscode 默认是 `utf-8` 编码格式，所以会显示异常，同时 `utf-8` 兼容性更好，故调整文件默认编码格式。

以 `practical_exercises/10_day_practice/day2/枚举类型.cpp` 为例：
乱码示例：
<img width="1735" alt="image" src="https://user-images.githubusercontent.com/7598833/210233346-85d77879-66fb-40eb-9163-130ebfdc97f6.png">

优化后的示例：
<img width="1782" alt="image" src="https://user-images.githubusercontent.com/7598833/210233559-32dac0b2-80ab-4030-a9c9-703cc49085fc.png">

本次修改将仓库内所有的 `GBK` cpp 文件都改成 `utf-8` 格式。

**Comment by tracyxiong1** [comment]
#254

**Comment by Light-City** [comment]
> 

thanks，please put your pr on this repo.

**Comment by Light-City** [comment]
this related pr https://github.com/Light-City/CPlusPlusThings/pull/254 has been closed.
