### ISSUE TITLE
Fix a small bug

### ISSUE THREAD

**Issue by ruohai0925** [Light-City/CPlusPlusThings#255]
https://github.com/Light-City/CPlusPlusThings/tree/master/basic_content/sizeof#4%E5%8E%9F%E5%88%994%E4%B8%8E5

原则4与5中

有一句代码应该是

class C1:public A1

而不是

class C1:public A

**Comment by stoody-dev** [comment]
assign me

**Comment by laialaodi** [comment]
建议直接 PR

**Comment by laialaodi** [comment]
@Light-City come and fix bug!
