### ISSUE TITLE
这里的注释部分写错了吧

### ISSUE THREAD

**Issue by guben** [Light-City/CPlusPlusThings#26]
`    Base ptr;
    Derived d;
    Base *pt = new Derived(); // 基类指针指向派生类实例
    Base &pp = ptr; // 基类引用指向基类实例
    Base &p = d; // 基类引用指向派生类实例
    cout<<"基类对象直接调用"<<endl;
    ptr.fun1();
    cout<<"基类引用指向派生类实例"<<endl;
    pp.fun1(); 
    cout<<"基类指针指向派生类实例并调用虚函数"<<endl;
    pt->fun1();
    cout<<"基类引用指向基类实例并调用虚函数"<<endl;
    p.fun1();`

**Comment by Light-City** [comment]
> 基类指针指向派生类实例

Thanks ！ 已fix
