### ISSUE TITLE
‘int Base::value’ is private within this context

### ISSUE THREAD

**Issue by warmbodytt** [Light-City/CPlusPlusThings#266]
https://github.com/Light-City/CPlusPlusThings/blob/c68db8a2294427e969680c7ee45571d83ccf590f/basic_content/using/derived_base.cpp#L35

**Comment by laialaodi** [comment]
I cannot understand this code :(

**Comment by laialaodi** [comment]
I think this is just a example

**Comment by laialaodi** [comment]
个人认为这就是为了让人知道 `protect` 限定符的作用
