### ISSUE TITLE
关于sizeof原则2，运行结果不一样

### ISSUE THREAD

**Issue by just-OneKey** [Light-City/CPlusPlusThings#27]
sizeof那些事，原则2
这是我复制下去的代码：
`#include<iostream>
using namespace std;
class A
{
    public:
        char b;
        virtual void fun() {};
        static int c;
        static int d;
        static int f;
};

int main()
{
    /**
     * @brief 16  字节对齐、静态变量不影响类的大小、vptr指针=8
     */
    A a;
    cout<<"A size:"<<sizeof(A)<<endl; 
    cout<<"a size:"<<sizeof(a)<<endl;
    return 0;
}`
我的运行结果并不是16，而是8：
![image](https://user-images.githubusercontent.com/42026869/84123196-15f83780-aa6c-11ea-86d4-68ef2cd54543.png)

求大佬讲解一下是什么原因。
运行环境 ：win10 + g++编译器 + inter i7

**Comment by newdee** [comment]
@just-OneKey 
static不占用类的空间，是独立放置的。
虚表指针，你用32位编译就是4个字节，char字节对齐，占4个字节，一共是8个字节。
64位编译才是16个字节

**Comment by Light-City** [comment]
> @just-OneKey
> static不占用类的空间，是独立放置的。
> 虚表指针，你用32位编译就是4个字节，char字节对齐，占4个字节，一共是8个字节。
> 64位编译才是16个字节
> 
> 如果确认没问题，可以close了

正解

**Comment by just-OneKey** [comment]
> @just-OneKey
> static不占用类的空间，是独立放置的。
> 虚表指针，你用32位编译就是4个字节，char字节对齐，占4个字节，一共是8个字节。
> 64位编译才是16个字节
> 
> 如果确认没问题，可以close了

感谢大佬，确实是32位g++，更换成64位的之后输出就是16了。
