### ISSUE TITLE
子类对父类成员的访问权限跟如何继承没有任何关系?

### ISSUE THREAD

**Issue by naivedriver** [Light-City/CPlusPlusThings#275]
这个结论是错的吧？
正确的子类对于其父类成员的访问权限：
父类的private成员，无论继承方式如何，子类都不可访问
父类的public成员，派生类的访问权限= min(public, 继承方式)
父类的protect成员，派生类的访问权限= min(protect, 继承方式)

**Comment by c-cpp-a** [comment]
我记得C++标准里有关于这个的，但不同版本的标准不同意，不确定这个项目编写的是关于哪个版本的
