### ISSUE TITLE
最后，当把一个const常量的地址赋值给ptr时候，由于ptr指向的是一个变量，而不是const常量，所以会报错，出现：const int* -> int *错误！

### ISSUE THREAD

**Issue by lhx24** [Light-City/CPlusPlusThings#295]
“最后，当把一个const常量的地址赋值给ptr时候，由于ptr指向的是一个变量，而不是const常量，所以会报错，出现：const int* -> int *错误！“”
问题在于，如果我们将指向const类型的变量的地址赋给指针变量，那么这个指针变量的值也就变成了一个常量。所以才要变成指向常量的常指针。 小编说“由于ptr指向的是一个变量，而不是const常量”，有偏差而且互相矛盾，因为常指针ptr是一个指针它指向int num=0;
这个在文中小编说也是正确，那他ptr就是指向一个变量，而不是const常量。所以我认为是，常指针指向了一个常量，使得常指针原来指向的值可以修改变成不可以修改，编译器认为不合理，解决方法才是使常指针升级未指向常量的常指针。
int main() {
    int num = 0;
    int* const ptr = &num; // 常量指针，指向非常量的常指针
    *ptr = 1; // 正确，常量指针指向的地址的值可以修改
    ptr++; // 错误，常量指针本身的地址不可修改
    return 0;
}

**Comment by Light-City** [comment]
cool!
