### ISSUE TITLE
docker部署项目的问题

### ISSUE THREAD

**Issue by AjaxZhan** [Light-City/CPlusPlusThings#297]
运行环境：Ubuntu，
问题：docker pull项目后，运行`docker run -idt -v /Users/light/CPlusPlusThings:/home/admin/CPlusPlusThings --cap-add sys_ptrace --ulimit core=-1 --privileged --name cplusplusthings cplusplusthings:latest` 会提示错误信息：Unable to find image 'cplusplusthings:latest' locally
docker: Error response from daemon: pull access denied for cplusplusthings, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by Light-City** [comment]
docker pull xingfranics/cplusplusthings:latest

**Comment by Light-City** [comment]
cplusplusthings:latest试试xingfranics/cplusplusthings:latest
