### ISSUE TITLE
关于英语表示书籍名的格式

### ISSUE THREAD

**Issue by laialaodi** [Light-City/CPlusPlusThings#298]
根据[知乎](https://www.zhihu.com/tardis/zm/art/96002549)，英语表示书名时应

- 添加下划线
- 斜体

二选一

因此项目英文名应为*Stories About C Plus Plus*，@Light-City 请求修改

**Comment by laialaodi** [comment]
怎么就 Close 了呢？问题没解决啊？光城是打算改但是还没改？

**Comment by Light-City** [comment]
> 怎么就 Close 了呢？问题没解决啊？光城是打算改但是还没改？

暂时先不改了
