### ISSUE TITLE
为啥这个判断会失效呢

### ISSUE THREAD

**Issue by qidouhai** [Light-City/CPlusPlusThings#299]
for (int n = 0; n < vtp.size(); n++) {
                            string t1 = get<0>(vtp[n]);
                            int t2 = get<1>(vtp[n]);
                            string t3 = get<2>(vtp[n]);
                            if (读取文件查找内容(stri)!= "标点符号") {
                                if (stri != t1 && i != t2) {
                                    vtp.push_back(make_tuple(stri, i, 读取文件查找内容(stri)));

                                }
                            }
                        }

**Comment by Light-City** [comment]
自己gdb一下
