### ISSUE TITLE
关于copy-swapAndADL.cpp swap使用的疑惑

### ISSUE THREAD

**Issue by jcraffael** [Light-City/CPlusPlusThings#301]
你好，非常感谢这份教程！
我在学习c++编程风格里的copy and swap一节时有一个问题没有搞懂，想跟你请教下！
在使用方法4的代码时
```
smart_ptr &operator=(smart_ptr rhs) noexcept {
    swap(rhs);
    return *this;
}
```
我发现rhs.ptr_的值被转入this-ptr_之后就被释放了，导致在执行s1 = s2之后*s2.get()产生segfault。 对这一块我不太明白，使用swap之后s2的ptr_不应该被置换成s1的ptr_了吗？为何会被释放呢？

**Comment by Light-City** [comment]
请把代码贴全

**Comment by jcraffael** [comment]
就是这篇教程：
https://github.com/Light-City/CPlusPlusThings/blob/master/codingStyleIdioms/4_copy-swap/copy-swapAndADL.cpp

代码115行s1 = s2执行后，s2.get()就会返回一个空指针，我理解是在s1=s2赋值后s2的ptr_就被释放掉了。我的问题就是为何s2的ptr_会被释放掉，在赋值时调用swap为何不是交换s1 s2的ptr_指针呢

**Comment by Light-City** [comment]
> 就是这篇教程： https://github.com/Light-City/CPlusPlusThings/blob/master/codingStyleIdioms/4_copy-swap/copy-swapAndADL.cpp
> 
> 代码115行s1 = s2执行后，s2.get()就会返回一个空指针，我理解是在s1=s2赋值后s2的ptr_就被释放掉了。我的问题就是为何s2的ptr_会被释放掉，在赋值时调用swap为何不是交换s1 s2的ptr_指针呢

swap用的using std::swap; 没有深swap
