### ISSUE TITLE
2.2章节-输入输出流操作符重载问题

### ISSUE THREAD

**Issue by zceeyh0** [Light-City/CPlusPlusThings#302]
practical_exercises/key_exercises/io_operator_overload.cpp
![A48J~CMBXC340(K_9NVGD S](https://github.com/Light-City/CPlusPlusThings/assets/72344849/e0d3f0a5-df8b-4d51-9b26-3a83ebd19b19)
此处输入输出运算符重载的返回类型为Sale&，是否应该改为ostream&和istream&？
如果不返回流对象，类似cout << sale1 << sale2 << endl; 这种嵌套调用就会报错了。

**Comment by laialaodi** [comment]
> practical_exercises/key_exercises/io_operator_overload.cpp ![A48J~CMBXC340(K_9NVGD S](https://user-images.githubusercontent.com/72344849/248442512-e0d3f0a5-df8b-4d51-9b26-3a83ebd19b19.png) 此处输入输出运算符重载的返回类型为Sale&，是否应该改为ostream&和istream&？ 如果不返回流对象，类似cout << sale1 << sale2 << endl; 这种嵌套调用就会报错了。

e，能发一下完整代码吗谢谢

**Comment by laialaodi** [comment]
@zceeyh0 能发下完整代码吗谢谢

**Comment by laialaodi** [comment]
如果你要用 `cout << sale1 << sale2 << endl;` 这种嵌套写法那当然得改

**Comment by zceeyh0** [comment]
嗯，我就是想表达这个意思
