### ISSUE TITLE
关于单例模式：能否新增一个线程安全的单例模板类？

### ISSUE THREAD

**Issue by libaineu2004** [Light-City/CPlusPlusThings#303]
template <typename T>
class singleton_default
{
...
}

我知道boost实现了一个版本：
https://github.com/boostorg/container/blob/boost-1.82.0/include/boost/container/detail/singleton.hpp

**Comment by Light-City** [comment]
可以的

**Comment by libaineu2004** [comment]
> 可以的

另外，生产者和消费者，能否把【知识星球】里的condition_variable的源码包cv.zip上传到这个仓库？

**Comment by Light-City** [comment]
> > 可以的
> 
> 另外，生产者和消费者，能否把【知识星球】里的condition_variable的源码包cv.zip上传到这个仓库？

知识星球的东西暂时不开源 谢谢 如果感兴趣可以加入学习
