### ISSUE TITLE
中括号重载.cpp和动态数组.cpp有问题

### ISSUE THREAD

**Issue by regenttsui** [Light-City/CPlusPlusThings#31]
中括号重载.cpp至少应该补一个析构函数去释放employ指针所占用的内存。
动态数组.cpp有乱码，程序不完整。

**Comment by Light-City** [comment]
> 中括号重载.cpp至少应该补一个析构函数去释放employ指针所占用的内存。
> 动态数组.cpp有乱码，程序不完整。

全部修复，请查阅~
