### ISSUE TITLE
是不是注释写错了？CPlusPlusThings/practical_exercises/10_day_practice/day2 /pow.cpp中的注释。

### ISSUE THREAD

**Issue by LeonChenEPC** [Light-City/CPlusPlusThings#335]
CPlusPlusThings/practical_exercises/10_day_practice/day2 /pow.cpp

第一行注释
/* x的n次方.cpp */

但是pow.cpp的main中的sum输出，不是X的n次方。

**Comment by Light-City** [comment]
这里是说的那个函数，power(double x, int n) ，x^n
