### ISSUE TITLE
using那些事|改变访问性|

### ISSUE THREAD

**Issue by aemonair** [Light-City/CPlusPlusThings#37]
24行这里是想要写 private: 私有成员
然后子类里 using进行使用的吧。

class Base {
...
    protected:  //私有
        int value;
};

**Comment by aemonair** [comment]
https://github.com/Light-City/CPlusPlusThings/blob/master/basic_content/using/derived_base.cpp

**Comment by Light-City** [comment]
> 24行这里是想要写 private: 私有成员
> 然后子类里 using进行使用的吧。
> 
> class Base {
> ...
> protected: //私有
> int value;
> };

已经fix了，当时写的，忘记更新了，谢谢！
