### ISSUE TITLE
enum那些事

### ISSUE THREAD

**Issue by GZW-art** [Light-City/CPlusPlusThings#38]
关于解决作用域不受限带来的命名冲突的经典做法，“这里使用结构体而非类......”其中第二点好像有点问题，这是在C++中，是可以有函数的。

**Comment by Light-City** [comment]
> 关于解决作用域不受限带来的命名冲突的经典做法，“这里使用结构体而非类......”其中第二点好像有点问题，这是在C++中，是可以有函数的。

是的，已经把那句话删掉了，可以加函数。
