### ISSUE TITLE
引用是个“对象”？

### ISSUE THREAD

**Issue by hi60year** [Light-City/CPlusPlusThings#4]
https://github.com/Light-City/CPlusPlusThings/tree/master/basic_content/pointer_refer

>这个操作符一般需要返回一个引用对象

**Comment by Light-City** [comment]
文中我介绍的是operator []一般需要返回引用，举个例子：vector<int> v;
v[1]=10，我们对Index=1的元素修改为10，所以需要返回引用，具体也可以看源码去了解。

**Comment by hi60year** [comment]
@Light-City You're not listening to me. 我的意思是引用不是对象。
