### ISSUE TITLE
this指针那些事中Person构造函数的第一个参数应该为const char *n

### ISSUE THREAD

**Issue by XiongDanqi** [Light-City/CPlusPlusThings#42]

**Comment by KvantXiu** [comment]
## 报错信息
* 1、No instance of constructor "Person::Person" matches the argument list.
解决方案：
在Person的构造函数中
``` c++
Person(char *n, int a, SexType s)
```
* 2、strcpy unsafe
解决方案：
不再使用 cstdlib，换做string库。
