### ISSUE TITLE
Print result

### ISSUE THREAD

**Issue by zhang-b-x** [Light-City/CPlusPlusThings#46]
https://github.com/Light-City/CPlusPlusThings/blob/993d42631e1dc6b87fb14a6a460c67307abdf8b2/practical_exercises/10_day_practice/day1/%E6%89%93%E5%8D%B0%E7%BB%83%E4%B9%A0.cpp#L11
f <= 2 * i 改成 f <= 2 * i - 1，打印结果是否要好一些。

**Comment by Light-City** [comment]
> https://github.com/Light-City/CPlusPlusThings/blob/993d42631e1dc6b87fb14a6a460c67307abdf8b2/practical_exercises/10_day_practice/day1/%E6%89%93%E5%8D%B0%E7%BB%83%E4%B9%A0.cpp#L11
> 
> 
> f <= 2 * i 改成 f <= 2 * i - 1，打印结果是否要好一些。

你可以测试一下~代码最好都动手一下，这样效果好~
