### ISSUE TITLE
sizeof

### ISSUE THREAD

**Issue by Sandy1230** [Light-City/CPlusPlusThings#47]
sizeof 在Windows和Linux下是不是有一些不一样，在派生类虚继承多个虚函数中,在Windows得到的结果是8, 8, 32

**Comment by Light-City** [comment]
> sizeof 在Windows和Linux下是不是有一些不一样，在派生类虚继承多个虚函数中,在Windows得到的结果是8, 8, 32

注意32位与64位系统区别！

**Comment by Sandy1230** [comment]
按照例程64位下得到的应该是8，8，16，但我得到的是8，8，32

**Comment by Light-City** [comment]
> 按照例程64位下得到的应该是8，8，16，但我得到的是8，8，32

那有可能是编译器问题呢，例如：字节对齐的影响导致~

**Comment by Sandy1230** [comment]
按照例程64位下得到的应该是8，8，16，但我得到的是8，8，32
