### ISSUE TITLE
拼写错误

### ISSUE THREAD

**Issue by wxjcn** [Light-City/CPlusPlusThings#51]
https://github.com/Light-City/CPlusPlusThings/blob/5354c10742b008f4081004ea22d7bc52a0e47fba/practical_exercises/10_day_practice/day5/%E7%BB%A7%E6%89%BF%E8%AE%BF%E9%97%AE%E6%9D%83%E9%99%90/%E7%A7%81%E6%9C%89%E7%BB%A7%E6%89%BF.cpp#L12

应该是class derived:private Base{

**Comment by Light-City** [comment]
> https://github.com/Light-City/CPlusPlusThings/blob/5354c10742b008f4081004ea22d7bc52a0e47fba/practical_exercises/10_day_practice/day5/%E7%BB%A7%E6%89%BF%E8%AE%BF%E9%97%AE%E6%9D%83%E9%99%90/%E7%A7%81%E6%9C%89%E7%BB%A7%E6%89%BF.cpp#L12
> 
> 应该是class derived:private Base{

Thanks 已修正
