### ISSUE TITLE
关于 inline 介绍中的遗漏

### ISSUE THREAD

**Issue by frederick-vs-ja** [Light-City/CPlusPlusThings#6]
[页面链接](https://github.com/Light-City/CPlusPlusThings/tree/master/basic_content/inline)

语义上，拥有外部链接的 inline 函数允许多个翻译单元（链接之前分别编译的内容，多数时候一个源文件对应一个翻译单元）同时有该函数的定义，只要这些定义等同。一个函数是否被内联是在标准中没有语义区别。

现在的有些编译器在开优化的时候不会在意 `inline` ，从而 `inline` 的作用更多是“允许多个翻译单元中的各一个定义”。 C++17 中的 inline 变量也是如此。

虚函数是否内联在有的 ABI 上会存在影响，参考[此处](https://libcxxabi.llvm.org/)。

另外目前缺少 inline namespace 的介绍。

**Comment by hi60year** [comment]
遗漏就算了吧，，貌似using那里*using directive*和*using declaration*都没区分。。。

**Comment by Light-City** [comment]
> 遗漏就算了吧，，貌似using那里_using directive_和_using declaration_都没区分。。。

我一个人在维护，只发表自己目前学习的东西，当然还不全，期待大家补充～，谢谢

**Comment by Light-City** [comment]
> [页面链接](https://github.com/Light-City/CPlusPlusThings/tree/master/basic_content/inline)
> 
> 语义上，拥有外部链接的 inline 函数允许多个翻译单元（链接之前分别编译的内容，多数时候一个源文件对应一个翻译单元）同时有该函数的定义，只要这些定义等同。一个函数是否被内联是在标准中没有语义区别。
> 
> 现在的有些编译器在开优化的时候不会在意 `inline` ，从而 `inline` 的作用更多是“允许多个翻译单元中的各一个定义”。 C++17 中的 inline 变量也是如此。
> 
> 虚函数是否内联在有的 ABI 上会存在影响，参考[此处](https://libcxxabi.llvm.org/)。
> 
> 另外目前缺少 inline namespace 的介绍。

谢谢指出，后续更新，也欢迎发表看法，pr~
