### ISSUE TITLE
const那些事：7.类中使用const

### ISSUE THREAD

**Issue by Pealicx** [Light-City/CPlusPlusThings#61]
![image](https://user-images.githubusercontent.com/20147750/88684237-361cac80-d127-11ea-8288-c76acac910cf.png)

代码中并没有体现const对象默认调用const成员函数。

**Comment by 20minute** [comment]
`int Apple::add(int num) {
	cout << "add func  " << num << endl;
	return num;
}
int Apple::add(int num) const {
	cout << "add func const " << num << endl;
	return num;
}`

改成这样就能看出来了，const对象默认调用 const成员函数
