### ISSUE TITLE
关于 sizeof 那些事

### ISSUE THREAD

**Issue by taseikyo** [Light-City/CPlusPlusThings#69]
由于 long 在不同操作系统下所占用的字节数不同，建议使用 long long 举例😂
![277239-20190512200116254-806357247](https://user-images.githubusercontent.com/23132915/90842293-7e7b6300-e391-11ea-8b76-7cbd6c805a7e.png)
比如 [原则 4 与 5](https://github.com/Light-City/CPlusPlusThings/tree/master/basic_content/sizeof#4%E5%8E%9F%E5%88%994%E4%B8%8E5)
在 windows (64) 下得到的结果如下
```
>> a.exe
8      
16     
12     
8      
```

**Comment by Light-City** [comment]
> 由于 long 在不同操作系统下所占用的字节数不同，建议使用 long long 举例
> ![277239-20190512200116254-806357247](https://user-images.githubusercontent.com/23132915/90842293-7e7b6300-e391-11ea-8b76-7cbd6c805a7e.png)
> 比如 [原则 4 与 5](https://github.com/Light-City/CPlusPlusThings/tree/master/basic_content/sizeof#4%E5%8E%9F%E5%88%994%E4%B8%8E5)
> 在 windows (64) 下得到的结果如下
> 
> ```
> >> a.exe
> 8      
> 16     
> 12     
> 8      
> ```

表格给的不错，收到~感谢～
