### ISSUE TITLE
CPlusPlusThings/ practical_exercises / key_exercises / 函数模板.cpp

### ISSUE THREAD

**Issue by DaXiaoSHI** [Light-City/CPlusPlusThings#70]
函数compareMax的特化形式，在例子中未被调用，是由于特化函数的参数类型是char *而不是const char *,导致调用时匹配不到特化函数

**Comment by maomaonwpu** [comment]
没错，可改成如下
template<> const char* compareMax<const char*>(const char* a,const char* b){
    return strcmp(a,b)>=0 ? a : b;
}
