### ISSUE TITLE
vptr_vtable那些事

### ISSUE THREAD

**Issue by MingliangLu** [Light-City/CPlusPlusThings#74]
https://light-city.club/sc/basic_content/vptr_vtable/

Fun getAddr(void* obj,unsigned int offset)
{
    cout<<"======================="<<endl;
    void* vptr_addr = (void *)*(unsigned long *)obj;  
    printf("vptr_addr:%p\n",vptr_addr);
    void* func_addr = (void *)*((unsigned long *)vptr_addr+offset);
    printf("func_addr:%p\n",func_addr);
    return (Fun)func_addr;
}
[windows]在64位系统下unsigned long是4bytes，但是*vptr_addr是8byte，(unsigned long *)vptr_addr+offset，会出现问题。

**Comment by Light-City** [comment]
> https://light-city.club/sc/basic_content/vptr_vtable/
> 
> Fun getAddr(void* obj,unsigned int offset)
> {
> cout<<"======================="<<endl;
> void* vptr_addr = (void _)_(unsigned long _)obj; printf("vptr_addr:%p\n",vptr_addr); void_ func_addr = (void _)_((unsigned long _)vptr_addr+offset); printf("func_addr:%p\n",func_addr); return (Fun)func_addr; } [windows]在64位系统下unsigned long是4bytes，但是_vptr_addr是8byte，(unsigned long *)vptr_addr+offset，会出现问题。

我这个是在linux64开发的，见最前面说的，其他操作系统使用自己需要修改一下。
