### ISSUE TITLE
文件例题/12-7.cpp，cout << ch 打印不正常

### ISSUE THREAD

**Issue by 1ADZX** [Light-City/CPlusPlusThings#79]
cout << ch,打印输出的竟然1 2 3 4 5 6 7 8 9 : ;
然后判断了一下写入的数据，应该是符合逻辑的，为什么这里读取的数据，输出却不符合逻辑？

**Comment by daidai21** [comment]
https://baike.baidu.com/item/ASCII

看下ASCII码表，这里输出的是1 ~ 90 的ASCII
