### ISSUE TITLE
sizeof那些事-虚继承

### ISSUE THREAD

**Issue by KvantXiu** [Light-City/CPlusPlusThings#83]
虚继承的一些问题
``` c++
// 必要头文件
#include <iostream>

using namespace std;

/*
// 虚继承问题
*/
class A
{
	virtual void fun() {}
};

class B
{
	virtual void fun2() {}
};

class C :virtual public A, virtual public B
{
public:
	virtual void func3() {}
};

int main()
{
	// 派生类虚继承多个虚函数，会继承所有的虚函数vptr
	cout << "sizeof(A) = " << sizeof(A) << endl;  // 输出 8
	cout << "sizeof(B) = " << sizeof(B) << endl;  // 输出 8 
	cout << "sizeof(C) = " << sizeof(C) << endl;  // 输出32？？
	return 0;
}
```

**Comment by Light-City** [comment]
> 虚继承的一些问题
> 
> ```c++
> // 必要头文件
> #include <iostream>
> 
> using namespace std;
> 
> /*
> // 虚继承问题
> */
> class A
> {
> 	virtual void fun() {}
> };
> 
> class B
> {
> 	virtual void fun2() {}
> };
> 
> class C :virtual public A, virtual public B
> {
> public:
> 	virtual void func3() {}
> };
> 
> int main()
> {
> 	// 派生类虚继承多个虚函数，会继承所有的虚函数vptr
> 	cout << "sizeof(A) = " << sizeof(A) << endl;  // 输出 8
> 	cout << "sizeof(B) = " << sizeof(B) << endl;  // 输出 8 
> 	cout << "sizeof(C) = " << sizeof(C) << endl;  // 输出32？？
> 	return 0;
> }
> ```

不是32是16。
