### ISSUE TITLE
中括号重载的例子里有内存泄露吧?

### ISSUE THREAD

**Issue by toilaj** [Light-City/CPlusPlusThings#97]
SalaryManaege析构的时候只delete了employ，但没有delete employ里的name。

**Comment by pbmenglq** [comment]
> loy里

应该是，我改了下：
(1)不用字符串，改用string；
(2)析构函数里释放掉指针。

#include <iostream>
#include <string>
using namespace std;
struct Person{                		//职工基本信息的结构
		double salary;
		string name;
};
class SalaryManaege{
		Person *employ;          	 //存放职工信息的数组
		int max;                  		//数组下标上界
		int n;                    		//数组中的实际职工人数
public:
	SalaryManaege(int Max=0){
		max=Max;
		n=0;
		employ=new Person[max]; //内存泄漏？
	}
	~SalaryManaege(){
		delete [] employ;
	}
    double &operator[](const string Name) {       	//重载[]，返回引用
		Person *p;
		for(p=employ;p<employ+n;p++)   
			//如果存在处理   	
			if(p->name == Name)
				return p->salary;
		//不存在情况处理
		p=employ + n++; 
		p->name = Name;
		p->salary=0;
		return p->salary;
	}

	void display(){      								
		for(int i=0;i<n;i++)
			cout<<employ[i].name<<"   "<<employ[i].salary<<endl;
		}
};
int main(){
    SalaryManaege s(5);
    s["张三"]=2188.88; // 返回的引用，可以赋值
    s["里斯"]=1230.07;
    s["王无"]=3200.97;
    cout<<"张三\t"<<s["张三"]<<endl;          cout<<"里斯\t"<<s["里斯"]<<endl;
    cout<<"王无\t"<<s["王无"]<<endl;
  
    cout<<"-------下为display的输出--------\n\n";
    s.display();
    system("pause");
}
